# -*- coding: utf-8 -*-
"""NNDL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UodB1lNX9QEYf2ggLWdJqseCuHYvJdEB
"""

import tensorflow as tf
from tensorflow.keras import layers,models
import numpy as np
import  matplotlib.pyplot as plt
import cv2

(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()
x_train = x_train/225.0
x_test = x_test/225.0

classifier = models.Sequential([
    layers.Reshape((28,28,1), input_shape=(28,28)),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

classifier.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

classifier.fit(x_train, y_train, epochs=5, batch_size=32)

def predict_digit(image):
    image = cv2.resize(image, (28,28))
    image = image / 255.0
    image = image.reshape(1,28,28)

    prediction = classifier.predict(image)
    return np.argmax(prediction)

plt.imshow(x_test[0], cmap='gray')
print("Predicted Digit:", predict_digit(x_test[0]))



import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, Rescaling
import matplotlib.pyplot as plt
import numpy as np

# Load dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Model
model = Sequential([
    Rescaling(1./255, input_shape=(28, 28)),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
model.fit(
    x_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test, y_test)
)

# Evaluate
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", test_accuracy)

# Predictions
predictions = model.predict(x_test)

# Show 2 digits
plt.figure(figsize=(6, 3))

for i in range(2):
    plt.subplot(1, 2, i + 1)
    plt.imshow(x_test[i], cmap='gray')
    plt.title(f"Predicted: {np.argmax(predictions[i])}, True: {y_test[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

